services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    volumes:
      - ./zookeeper/zookeeper1.properties:/etc/kafka/zookeeper.properties
      - zookeeper_data1:/var/lib/zookeeper/data
      - zookeeper_log1:/var/lib/zookeeper/log
    networks:
      - kafka_network

  zookeeper2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    volumes:
      - ./zookeeper/zookeeper2.properties:/etc/kafka/zookeeper.properties
      - zookeeper_data2:/var/lib/zookeeper/data
      - zookeeper_log2:/var/lib/zookeeper/log
    networks:
      - kafka_network

  zookeeper3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    volumes:
      - ./zookeeper/zookeeper3.properties:/etc/kafka/zookeeper.properties
      - zookeeper_data3:/var/lib/zookeeper/data
      - zookeeper_log3:/var/lib/zookeeper/log
    networks:
      - kafka_network

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka/server1.properties:/etc/kafka/server.properties
      - kafka_data1:/var/lib/kafka/data
    networks:
      - kafka_network

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka/server2.properties:/etc/kafka/server.properties
      - kafka_data2:/var/lib/kafka/data
    networks:
      - kafka_network

  kafka3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka3
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka/server3.properties:/etc/kafka/server.properties
      - kafka_data3:/var/lib/kafka/data
    networks:
      - kafka_network

  content-delivery-service:
    build:
      context: ./content-delivery-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - KAFKA_HOST=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKA_TRANSCODE_TOPIC=transcode-requests
      - REDIS_URL=${REDIS_URL}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka_network

  transcoding-service:
    build:
      context: ./transcoding-service
    ports:
      - "3006:3006"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - KAFKA_HOST=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKA_TRANSCODE_TOPIC=video-transcoding
      - HEALTH_CHECK_PORT=3001
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - ./transcoding-service/videos/input:/app/videos/input
      - ./transcoding-service/videos/output:/app/videos/output
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka_network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_SENDER=${MAILGUN_SENDER}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
      - KAFKA_BROKER=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka_network

  user-management-service:
    build:
      context: ./user-management-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BROKER=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka_network

  course-management-service:
    build:
      context: ./course-management-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BROKER=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka_network

  assessment-service:
    build:
      context: ./assessment-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BROKER=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka_network

volumes:
  zookeeper_data1:
  zookeeper_log1:
  zookeeper_data2:
  zookeeper_log2:
  zookeeper_data3:
  zookeeper_log3:
  kafka_data1:
  kafka_data2:
  kafka_data3:

networks:
  kafka_network:
    driver: bridge