_format_version: "2.1"
_transform: true

services:
  - name: user-management-service
    url: http://user-management-service:3000
    routes:
      - name: user-management-route
        paths:
          - /api/v1/users
          - /api/v1/profile

  - name: course-management-service
    url: http://course-management-service:3000
    routes:
      - name: course-management-route
        paths:
          - /api/v1/courses

  - name: content-delivery-service
    url: http://content-delivery-service:3000
    routes:
      - name: content-delivery-route
        paths:
          - /api/v1/content

  - name: assessment-service
    url: http://assessment-service:3000
    routes:
      - name: assessment-route
        paths:
          - /api/v1/assessments

  - name: transcoding-service
    url: http://transcoding-service:3000
    routes:
      - name: transcoding-route
        paths:
          - /api/v1/transcoding

  - name: notification-service
    url: http://notification-service:3000
    routes:
      - name: notification-route
        paths:
          - /api/v1/notifications
