version: '3.8'

services:
  app:
    build: .
    container_name: user-management-service
    ports:
      - "3007:3007"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3007
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
    networks:
      - moocflix-network
    command: npm start

networks:
  moocflix-network:
    external: true