version: '3.8'

services:
  app:
    build: .
    ports:
      - "3007:3007"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3007
    command: npm start