global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'user-management'
      static_configs:
          - targets: ['user-management:3007']
      metrics_path: '/api/v1/metrics'
