services:
  content-delivery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content-delivery-service
    ports:
      - "3006:3006"
    env_file: .env
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - content-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - KAFKAJS_NO_PARTITIONER_WARNING=1

networks:
  content-network:
    driver: bridge 