# course-routes.yml
_format_version: "3.0"
routes:
  - name: course-management
    paths:
      - /api/v1/courses/create
      - /api/v1/courses/:courseId
      - /api/v1/courses/:courseId/update
      - /api/v1/courses/:courseId/delete
    strip_path: false
    service: course-management
    methods:
      - GET
      - POST
      - PUT
      - DELETE

  - name: course-modules
    paths:
      - /api/v1/courses/:courseId/modules
      - /api/v1/courses/:courseId/modules/create
      - /api/v1/courses/:courseId/modules/:moduleId/update
      - /api/v1/courses/:courseId/modules/:moduleId/delete
    strip_path: false
    service: course-management
    methods:
      - GET
      - POST
      - PUT
      - DELETE

  - name: course-enrollment
    paths:
      - /api/v1/courses/:courseId/enroll
      - /api/v1/courses/:courseId/students
    strip_path: false
    service: course-management
    methods:
      - GET
      - POST
