name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - run: npm ci
            - run: npm test
            - run: npm run lint

    build:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - uses: actions/checkout@v2
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: your-registry/notification-service:latest
