version: '3'
services:
  course-management:
    build: .
    container_name: course-management
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=${MONGO_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_SSL=true
      - KAFKA_CA_CERT=/app/certs/ca-certificate.crt
      - KAFKA_CLIENT_KEY=/app/certs/user-access-key.key
      - KAFKA_CLIENT_CERT=/app/certs/user-access-certificate.crt
      - USER_MANAGEMENT_SERVICE_URL=http://user-management:3007
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - course_logs:/app/logs
      - ./certs:/app/certs:ro
    networks:
      - moocflix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 50000
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  moocflix-network:
    external: true 

volumes:
  course_logs: