version: '3.8'

services:
  course-management:
    build: .
    container_name: course-management
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/courses
      - KAFKA_BROKER=kafka:9092
      - USER_MANAGEMENT_SERVICE_URL=http://user-management:3007
    networks:
      - moocflix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - mongodb
      - kafka

  mongodb:
    image: mongo:latest
    container_name: mongodb-courses
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - moocflix-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-courses
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - moocflix-network

volumes:
  mongodb_data:

networks:
  moocflix-network:
    external: true 