_format_version: "2.1"
services:
  - name: content-delivery-service
    url: http://content-delivery-service:3000
    routes:
      - name: content-delivery-route
        paths:
          - /api/v1/content
