_format_version: "2.1"
services:
  - name: course-management-service
    url: http://course-management-service:3000
    routes:
      - name: course-management-route
        paths:
          - /api/v1/courses
