_format_version: "2.1"
services:
  - name: notification-service
    url: http://notification-service:3000
    routes:
      - name: notification-route
        paths:
          - /api/v1/notifications
